name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-tests:
    name: Build tests
    runs-on: ubuntu-latest
    container: cbrzeszczot/wonderful:wswan-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Build
        run: make

      - name: Archive ROM
        uses: actions/upload-artifact@v4
        with:
          name: Test programs
          path: build-all/

